networks:
  caddy:
    external: true
services:
  notifiarr:
    container_name: notifiarr
    user: 1000:1000
    restart: unless-stopped
    entrypoint:
      - /notifiarr
    image: golift/notifiarr:0.9.1
    networks:
      - caddy
    ports:
      - 5454:5454/tcp
    volumes:
      - /etc/machine-id:/etc/machine-id:ro
      - /tank:/storage/1:ro
      - /nvme/docker_appdata/Notifiarr:/config
      - /var/run/utmp:/var/run/utmp:ro
  jellyfin:
    container_name: jellyfin
    user: 1000:1000
    restart: unless-stopped
    group_add:
      - "44"
      - "992" # add to the render group for transcoding
    devices:
      - /dev/dri:/dev/dri
    image: ghcr.io/jellyfin/jellyfin:10.11
    ports:
      - 1900:1900/udp
      - 7359:7359/udp
      - 8096:8096/tcp
      - 8920:8920/tcp
    environment:
      - JELLYFIN_DATA_DIR=/config/data
      - JELLYFIN_CONFIG_DIR=/config
      - JELLYFIN_LOG_DIR=/config/log
      - JELLYFIN_CACHE_DIR=/config/cache
      - TZ=Europe/Dublin
    volumes:
      - /nvme/docker_appdata/jellyfin:/config
      - /tank/data/media:/data/media
    networks:
      - caddy
  jellyseerr:
    command:
      - pnpm
      - start
    container_name: jellyseerr
    user: 1000:1000
    image: fallenbagel/jellyseerr:2.7.3@sha256:4538137bc5af902dece165f2bf73776d9cf4eafb6dd714670724af8f3eb77764
    ports:
      - 5055:5055/tcp
    restart: unless-stopped
    networks:
      - caddy
    volumes:
      - /nvme/docker_appdata/jellyseerr:/app/config
  prowlarr:
    container_name: prowlarr
    restart: unless-stopped
    image: ghcr.io/home-operations/prowlarr:rolling@sha256:1a8a4b11972b2e62671b49949c622b8cb1110e2b5c77199ac795a6d79fe106e8
    user: 1000:1000
    ports:
      - 9696:9696/tcp
    volumes:
      - /nvme/docker_appdata/prowlarr:/config
    networks:
      - caddy
    environment:
      - TZ=Europe/Dublin
  radarr:
    container_name: radarr
    restart: unless-stopped
    image: ghcr.io/home-operations/radarr:rolling@sha256:73fbdba72dcde5fec16264e63a9daba7829b5c2806a75615463a67117b100de3
    user: 1000:1000
    ports:
      - 7878:7878/tcp
    volumes:
      - /nvme/docker_appdata/radarr:/config
      - /tank/data:/data
    networks:
      - caddy
    environment:
      - TZ=Europe/Dublin
  sabnzbd:
    container_name: sabnzbd
    image: ghcr.io/home-operations/sabnzbd:rolling@sha256:da57e01cdebc547852b6df85c8df8c0e4d87792742c7608c5590dc653b184e8c
    user: 1000:1000
    restart: unless-stopped
    ports:
      - 8080:8080/tcp
    volumes:
      - /nvme/docker_appdata/sabnzbd:/config
      - /nvme/docker_appdata/sabnzbd/incomplete:/data/usenet/incomplete
      - /tank/data/usenet:/data/usenet
    networks:
      - caddy
    environment:
      - TZ=Europe/Dublin
  sonarr:
    container_name: sonarr
    restart: unless-stopped
    user: 1000:1000
    networks:
      - caddy
    image: ghcr.io/home-operations/sonarr:rolling@sha256:0a1b8f5cb5b072f7ad8c6ff64a25dc512115d1a114ecf19a58a3b4f870207ddd
    ports:
      - 8989:8989/tcp
    volumes:
      - /nvme/docker_appdata/sonarr:/config
      - /tank/data:/data
    environment:
      - TZ=Europe/Dublin
