networks:
  caddy:
    external: true
services:
  notifiarr:
    container_name: notifiarr
    user: 1000:1000
    restart: unless-stopped
    entrypoint:
      - /notifiarr
    image: golift/notifiarr:0.8.3
    networks:
      - caddy
    ports:
      - 5454:5454/tcp
    volumes:
      - /etc/machine-id:/etc/machine-id:ro
      - /tank:/storage/1:ro
      - /nvme/docker_appdata/Notifiarr:/config
      - /var/run/utmp:/var/run/utmp:ro
  jellyfin:
    container_name: jellyfin
    user: 1000:1000
    restart: unless-stopped
    group_add:
      - "44"
      - "992" # add to the render group for transcoding
    devices:
      - /dev/dri:/dev/dri
    image: ghcr.io/jellyfin/jellyfin:10.10
    ports:
      - 1900:1900/udp
      - 7359:7359/udp
      - 8096:8096/tcp
      - 8920:8920/tcp
    environment:
      - JELLYFIN_DATA_DIR=/config/data
      - JELLYFIN_CONFIG_DIR=/config
      - JELLYFIN_LOG_DIR=/config/log
      - JELLYFIN_CACHE_DIR=/config/cache
      - TZ=Europe/Dublin
    volumes:
      - /nvme/docker_appdata/jellyfin:/config
      - /tank/data/media:/data/media
    networks:
      - caddy
  jellyseerr:
    command:
      - pnpm
      - start
    container_name: jellyseerr
    user: 1000:1000
    image: fallenbagel/jellyseerr:2.7.3@sha256:4538137bc5af902dece165f2bf73776d9cf4eafb6dd714670724af8f3eb77764
    ports:
      - 5055:5055/tcp
    restart: unless-stopped
    networks:
      - caddy
    volumes:
      - /nvme/docker_appdata/jellyseerr:/app/config
  prowlarr:
    container_name: prowlarr
    restart: unless-stopped
    image: ghcr.io/home-operations/prowlarr:rolling@sha256:3e5e091311bbea32612ef0f74cb56e9bd7f17a7a191a99b36c78825499390868
    user: 1000:1000
    ports:
      - 9696:9696/tcp
    volumes:
      - /nvme/docker_appdata/prowlarr:/config
    networks:
      - caddy
    environment:
      - TZ=Europe/Dublin
  radarr:
    container_name: radarr
    restart: unless-stopped
    image: ghcr.io/home-operations/radarr:rolling@sha256:b67ac38b70e9f0d2aee0be31be27fd25d9d35ed1f7204d012fd05effabc395f5
    user: 1000:1000
    ports:
      - 7878:7878/tcp
    volumes:
      - /nvme/docker_appdata/radarr:/config
      - /tank/data:/data
    networks:
      - caddy
    environment:
      - TZ=Europe/Dublin
  sabnzbd:
    container_name: sabnzbd
    image: ghcr.io/home-operations/sabnzbd:rolling@sha256:ecb57bd6257fbfbd9aee70d8ef3df8814b7270ae793fd1f44219ae73cacd519a
    user: 1000:1000
    restart: unless-stopped
    ports:
      - 8080:8080/tcp
    volumes:
      - /nvme/docker_appdata/sabnzbd:/config
      - /nvme/docker_appdata/sabnzbd/incomplete:/data/usenet/incomplete
      - /tank/data/usenet:/data/usenet
    networks:
      - caddy
    environment:
      - TZ=Europe/Dublin
  sonarr:
    container_name: sonarr
    restart: unless-stopped
    user: 1000:1000
    networks:
      - caddy
    image: ghcr.io/home-operations/sonarr:rolling@sha256:ca6c735014bdfb04ce043bf1323a068ab1d1228eea5bab8305ca0722df7baf78
    ports:
      - 8989:8989/tcp
    volumes:
      - /nvme/docker_appdata/sonarr:/config
      - /tank/data:/data
    environment:
      - TZ=Europe/Dublin
