services:
  dozzle:
    container_name: dozzle
    image: ghcr.io/amir20/dozzle:latest@sha256:c90494cbc3a9ca959634b89fdb3fdecbcbae1f690d7a567d0d356c6fda1d957c
    restart: unless-stopped
    ports:
      - 8888:8080/tcp
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
