services:
  dozzle:
    container_name: dozzle
    image: ghcr.io/amir20/dozzle:latest@sha256:c32ca7a443796de62a07afd621b17b6c6c073320cd8431493bb1fd84e3a1eff8
    restart: unless-stopped
    ports:
      - 8888:8080/tcp
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
