services:
  dozzle:
    container_name: dozzle
    image: ghcr.io/amir20/dozzle:latest@sha256:0ecac18a3491962002e9d6b9f9a363155131a4213e723ab86fc76dfee6e3cd8e
    restart: unless-stopped
    ports:
      - 8888:8080/tcp
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
