services:
  jellyfin:
    container_name: jellyfin
    user: "${PUID}:${PGID}"
    restart: unless-stopped
    group_add:
      - "44"
      - "992"
    devices:
      - /dev/dri:/dev/dri
    image: ghcr.io/jellyfin/jellyfin:10.11@sha256:45f648c382a0c8b552582fcea40e95cb17c5d475473a891cba0eb7523fb92112
    ports:
      - 1900:1900/udp
      - 7359:7359/udp
      - 8096:8096/tcp
      - 8920:8920/tcp
    environment:
      - JELLYFIN_DATA_DIR=/config/data
      - JELLYFIN_CONFIG_DIR=/config
      - JELLYFIN_LOG_DIR=/config/log
      - JELLYFIN_CACHE_DIR=/config/cache
      - TZ=${TZ}
    volumes:
      - ${APPDATA_ROOT}/jellyfin:/config
      - ${DATA_ROOT}/media:/data/media


  seerr:
    container_name: seerr
    image: ghcr.io/seerr-team/seerr:latest@sha256:f4768de5f616248d723e05891f3345a1402123775d03bf0890dbfedc0831bda1
    user: "${PUID}:${PGID}"
    ports:
      - 5055:5055/tcp
    restart: unless-stopped

    volumes:
      - ${APPDATA_ROOT}/seerr:/app/config
    environment:
      - TZ=${TZ}
      - LOG_LEVEL=info

  prowlarr:
    container_name: prowlarr
    restart: unless-stopped
    image: ghcr.io/home-operations/prowlarr:rolling@sha256:1a8a4b11972b2e62671b49949c622b8cb1110e2b5c77199ac795a6d79fe106e8
    user: "${PUID}:${PGID}"
    ports:
      - 9696:9696/tcp
    volumes:
      - ${APPDATA_ROOT}/prowlarr:/config

    environment:
      - TZ=${TZ}

  radarr:
    container_name: radarr
    restart: unless-stopped
    image: ghcr.io/home-operations/radarr:rolling@sha256:73fbdba72dcde5fec16264e63a9daba7829b5c2806a75615463a67117b100de3
    user: "${PUID}:${PGID}"
    ports:
      - 7878:7878/tcp
    volumes:
      - ${APPDATA_ROOT}/radarr:/config
      - ${DATA_ROOT}:/data
      - ${DOWNLOADS_ROOT}:/data/downloads

    environment:
      - TZ=${TZ}

  sonarr:
    container_name: sonarr
    restart: unless-stopped
    user: "${PUID}:${PGID}"

    image: ghcr.io/home-operations/sonarr:rolling@sha256:e679d9abf64f7a1edaf340f5c3fea20efed55fb1489ef8ba42f3404caed43590
    ports:
      - 8989:8989/tcp
    volumes:
      - ${APPDATA_ROOT}/sonarr:/config
      - ${DATA_ROOT}:/data
      - ${DOWNLOADS_ROOT}:/data/downloads
    environment:
      - TZ=${TZ}

  qui:
    container_name: qui
    image: ghcr.io/autobrr/qui:latest@sha256:c1531b69a116b2572f69c76e6e02990b20ca04ef6550c883009df9ebcade1aba
    user: "${PUID}:${PGID}"
    restart: unless-stopped
    ports:
      - 7476:7476/tcp
    volumes:
      - ${APPDATA_ROOT}/qui:/config
      - ${DOWNLOADS_ROOT}:/data/downloads
    environment:
      - TZ=${TZ}

  qbittorrent:
    container_name: qbittorrent
    image: ghcr.io/hotio/qbittorrent:release@sha256:fbff489ebe410ad4be3e86294298f40ccefb2cb410ccf2847f7c5819171dfb56
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
      - net.ipv6.conf.all.disable_ipv6=1
    ports:
      - 8080:8080/tcp
    volumes:
      - ${APPDATA_ROOT}/qbittorrent:/config
      - ${DOWNLOADS_ROOT}:/data/downloads
      - ${DATA_ROOT}/torrents:/data/torrents

    environment:
      - TZ=${TZ}
      - PUID=${PUID}
      - PGID=${PGID}
      - UMASK=002
      - VPN_ENABLED=true
      - VPN_CONF=wg0
      - VPN_PROVIDER=protonvpn
      - VPN_LAN_NETWORK=${VPN_LAN_NETWORK:-192.168.1.0/24}
      - VPN_LAN_LEAK_ENABLED=false
      - PRIVOXY_ENABLED=false
