networks:
  paperless:
    driver: bridge
  caddy:
    external: true
services:
  broker:
    image: docker.io/library/redis:8
    restart: unless-stopped
    volumes:
      - redisdata:/data
    networks:
      - paperless
  db:
    image: docker.io/library/postgres:17
    user: 1000:1000
    restart: unless-stopped
    volumes:
      - /nvme/docker_appdata/paperless-ngx/postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: paperless
      POSTGRES_USER: paperless
      POSTGRES_PASSWORD: paperless
    networks:
      - paperless
  webserver:
    image: ghcr.io/paperless-ngx/paperless-ngx:2.19.5@sha256:5f2a72fd7be42c6b1d8fa1751606a140452d4c3e6e829ae6b1b15e3c95129481 
    restart: unless-stopped
    user: 1000:1000
    container_name: paperless
    depends_on:
      - db
      - broker
      - gotenberg
      - tika
    ports:
      - 8000:8000
    networks:
      - caddy
      - paperless
    volumes:
      # Fast access on NVME
      - /nvme/docker_appdata/paperless-ngx/data:/usr/src/paperless/data
      - /nvme/docker_appdata/paperless-ngx/export:/usr/src/paperless/export
      - /nvme/docker_appdata/paperless-ngx/consume:/usr/src/paperless/consume
      # Actual documents on HDD
      - /tank/documents/paperless/media:/usr/src/paperless/media
    env_file: .env
    environment:
      PAPERLESS_REDIS: redis://broker:6379
      PAPERLESS_DBHOST: db
      PAPERLESS_TIKA_ENABLED: 1
      PAPERLESS_TIKA_GOTENBERG_ENDPOINT: http://gotenberg:3000
      PAPERLESS_TIKA_ENDPOINT: http://tika:9998
  gotenberg:
    image: docker.io/gotenberg/gotenberg:8.25
    user: 1000:1000
    restart: unless-stopped
    # The gotenberg chromium route is used to convert .eml files. We do not
    # want to allow external content like tracking pixels or even javascript.
    command:
      - gotenberg
      - --chromium-disable-javascript=true
      - --chromium-allow-list=file:///tmp/.*
    networks:
      - paperless
  tika:
    image: docker.io/apache/tika:latest
    user: 1000:1000
    restart: unless-stopped
    networks:
      - paperless
volumes:
  redisdata: null
