services:
  scrutiny:
    container_name: scrutiny
    image: ghcr.io/analogj/scrutiny:master-omnibus@sha256:cc88f7babededd75ec01a631bf53671d8be0acbe0c8a80f7ba4d41454a5fc52b
    restart: unless-stopped
    cap_add:
      - SYS_RAWIO
      - SYS_ADMIN
    ports:
      - 8081:8080 # webapp
      - 8086:8086 # influxDB admin
    volumes:
      - /run/udev:/run/udev:ro
      - /nvme/docker_appdata/scrutiny/config:/opt/scrutiny/config
      - /nvme/docker_appdata/scrutiny/influxdb:/opt/scrutiny/influxdb
    devices:
      - /dev/nvme0
      - /dev/nvme1
      - /dev/nvme2
      - /dev/sda
      - /dev/sdb
networks: {}
